services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: my_mariadb
    restart: always
    env_file: "./requirements/.env"
    secrets:
      - mysql_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      DB_PASSWORD_FILE: /run/secrets/db_password
    volumes: 
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$(cat /run/secrets/mysql_root_password) || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 2m
      start_interval: 5s

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: my_nginx
    restart: always
    secrets:
      - mysql_root_password
    env_file: ./requirements/.env
    ports: 
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: my_wordpress
    restart: always
    env_file: ./requirements/.env
    secrets:
      - wordpress_admin_password
      - wordpress_user_password
      - db_password
    depends_on: 
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm83"]
      interval: 10s
      timeout: 5s
      retries: 15
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception


volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hskrzypi/data/mariadb_database
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hskrzypi/data/wordpress_database

networks:
  inception:
    driver: bridge

secrets:
  mysql_root_password:
    file: ./requirements/secrets/mysql_root_password.txt
  wordpress_admin_password:
    file: ./requirements/secrets/wordpress_admin_password.txt
  wordpress_user_password:
    file: ./requirements/secrets/wordpress_user_password.txt
  db_password:
    file: ./requirements/secrets/db_password.txt