services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: my_mariadb
    restart: always
    env_file: ./requirements/env
    ports:
      - "3306:3306"
    volumes: 
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: my_nginx
    restart: always
    env_file: ./requirements/env
    ports: 
      - "443:443"
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: my_wordpress
    restart: always
    env_file: ./requirements/env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hskrzypi/data/mariadb_database
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hskrzypi/data/wordpress_database

networks:
  inception:
    driver: bridge
