services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: my_mariadb
    restart: always
    env_file: ./requirements/env
    ports:
      - "3306:3306"
    volumes: 
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hmariadb -P3306 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: my_nginx
    restart: always
    env_file: ./requirements/env
    ports: 
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: my_wordpress
    restart: always
    env_file: ./requirements/env
    depends_on: 
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm83"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hskrzypi/data/mariadb_database
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hskrzypi/data/wordpress_database

networks:
  inception:
    driver: bridge
